-- 코드를 입력하세요
/**
SELECT D.CAR_ID, D.CAR_TYPE, 
FLOOR(D.DAILY_FEE * ((100-C.DISCOUNT_RATE) / 100) * 30) FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
RIGHT JOIN 
(SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE FROM CAR_RENTAL_COMPANY_CAR A
RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE IN ('세단', 'SUV')
AND 
(DATE(B.START_DATE) > '2022-11-30'
OR DATE(B.END_DATE) < '2022-11-01')
UNION
SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE FROM CAR_RENTAL_COMPANY_CAR A
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE IN ('세단', 'SUV')
AND 
B.CAR_ID IS NULL) D
ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.DURATION_TYPE = '30일 이상'
HAVING (FEE >= 500000) AND (FEE < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
**/

-- 2, 3, 4, 5, 9, 10, 14, 16, 17X, 18, 19, 22, 23, 24, 25, 26X, 27, 29
-- 3, 18, 23, 27

SELECT 
    C.CAR_ID, 
    C.CAR_TYPE, 
    FLOOR(C.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE / 100)) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C
LEFT JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY RH 
    ON C.CAR_ID = RH.CAR_ID 
    AND RH.START_DATE <= '2022-11-30' 
    AND RH.END_DATE >= '2022-11-01'
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP 
    ON C.CAR_TYPE = DP.CAR_TYPE 
    AND DP.DURATION_TYPE = '30일 이상'
WHERE 
    C.CAR_TYPE IN ('세단', 'SUV')
    AND RH.HISTORY_ID IS NULL  -- 2022년 11월 1일~30일 사이에 대여 이력이 없는 자동차만 선택
HAVING 
    FEE >= 500000 AND FEE < 2000000
ORDER BY 
    FEE DESC, 
    C.CAR_TYPE ASC, 
    C.CAR_ID DESC;