-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, B.GENDER, COUNT(DISTINCT A.USER_ID) USERS
FROM ONLINE_SALE A
LEFT JOIN USER_INFO B
ON A.USER_ID = B.USER_ID
GROUP BY YEAR, MONTH, B.GENDER
HAVING B.GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER