-- 코드를 입력하세요

SELECT DISTINCT CATEGORY, PRICE, PRODUCT_NAME FROM FOOD_PRODUCT A
JOIN
(SELECT MAX(PRICE) AS MAX_PRICE FROM FOOD_PRODUCT
GROUP BY CATEGORY) B
ON A.PRICE = B.MAX_PRICE
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC