-- 코드를 입력하세요
SELECT 
    A.PRODUCT_ID, 
    A.PRODUCT_NAME, 
    A.PRICE * B.AMOUNT TOTAL_SALES
FROM FOOD_PRODUCT A
RIGHT JOIN
(SELECT PRODUCT_ID, SUM(AMOUNT) AMOUNT FROM FOOD_ORDER
WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY PRODUCT_ID) B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID