-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME, B.TOTAL_SALES FROM USED_GOODS_USER A
RIGHT JOIN
(SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES FROM USED_GOODS_BOARD
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000) B
ON A.USER_ID = B.WRITER_ID
ORDER BY B.TOTAL_SALES