WITH FRONT_END AS(
    SELECT SUM(CODE) CODE FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
    GROUP BY CATEGORY
)

SELECT
    CASE
        WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AND
        SKILL_CODE & (SELECT CODE FROM FRONT_END) THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
        WHEN SKILL_CODE & (SELECT CODE FROM FRONT_END) THEN 'C'
        ELSE NULL
    END GRADE,
    ID, 
    EMAIL
FROM DEVELOPERS
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID